apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      component: django
  template:
    metadata:
      labels:
        component: django
      namespace: default
    spec:
      containers:
        - name: django
          image: ghcr.io/pan-bellias/e-movies-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred