apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-ip
  labels:
    app: postgres # Defines app to create service for
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432