apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
spec:
  rules:
  - host:
    valueFrom:
      secretKeyRef:
        name: k8s-host
        key: HOST
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: django-clip 
            port:
              number: 8000